### PR TITLE
#139 - added EthToWei conversion

### PR DESCRIPTION
**Pull request by biboran**
As per #139 
* added an `EthToWei` to be able to convert a whole eth amount to a wei amount

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#140](https://github.com/blockstoreapp/web3swift/issues/140) is now in scope, role is `REV`

**Comment by biboran** [comment]
I think it might be a good idea to add [si prefixes](https://en.wikipedia.org/wiki/Metric_prefix)

**Comment by biboran** [comment]
We also need a `DoubleScalar` such that you could create `EthToWei(amount: 1.1)`

**Comment by biboran** [comment]
Lets do this one later

**Pull request closed without merging**
