### PR TITLE
#81 - refactored primitives

### PR DESCRIPTION
**Pull request by timofeys1**
To solve #81, #74, #68, #72, #26, #23 I redesigned the primitives.  

~~@driver733 Could you please start with a review. I'll specify how I solved each of the issue tomorrow. I'll also add some missing tests for `StringScalar`.~~

#23 - to solve missing private key object I added `PrivateKey` interface with an ability to compute address from and an ethereum implementation. 
#26 - I removed `Data(hex: String)` throwing ctor and replaced it with a `BytesFromHexString` and `BytesFromCompactHexString` objects.
#68 - I removed `Hex` interface and replaced it with 3 interfaces `BytesScalar`, `StringScalar` and `NumberScalar`. `HexString` object is now used for interpretation of validity of a certain string as hex and ambiguity discussed in #68 is resolved through `BigEndianCompactNumber` and `BytesFromCompactHexString`.
#74 - I redesign `QuantityParameter` to work with `NumberScalar`s exclusively.
#81 - I removed all of the interfaces for objects that were actually primitive values and conformed them to one of the new primitive interfaces. I removed `String` extensions and replaced them with different `StringScalar` objects. I added some decorators and proxies for working with hexes as numbers, bytes and strings. I added tests for all of the newly created objects.

### CODE REVIEW

**Comment by 0crat** [comment]
@driver733[/z](https://www.0crat.com/u/driver733) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@driver733[/z](https://www.0crat.com/u/driver733) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by biboran** [comment]
@0crat out

**Comment by 0crat** [comment]
Order was finished: +15 points just awarded to @driver733[/z](https://www.0crat.com/u/driver733)

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/BlockStoreApp/Web3Swift/issues/82#issuecomment-374848612))

@biboran The job [#82](https://github.com/blockstoreapp/web3swift/issues/82) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @biboran[/z](https://www.0crat.com/u/biboran)

**Pull request merged**
